version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: 0xmart_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P0s7@986611
      POSTGRES_DB: 0xmartdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - 0xmart_network

  redis:
    image: redis:7-alpine
    container_name: 0xmart_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - 0xmart_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 0xmart_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:P0s7@986611@postgres:5432/0xmartdb?schema=public
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - 0xmart_network

volumes:
  postgres_data:
  redis_data:

networks:
  0xmart_network:
    driver: bridge
