[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
oxmart_payment = "HwjrPzXD2LiotV6uFwMEzRYPKWw9FcVbnMk2vCW4mBPu"

[programs.devnet]
oxmart_payment = "HwjrPzXD2LiotV6uFwMEzRYPKWw9FcVbnMk2vCW4mBPu"

[programs.testnet]
oxmart_payment = "HwjrPzXD2LiotV6uFwMEzRYPKWw9FcVbnMk2vCW4mBPu"

[programs.mainnet]
oxmart_payment = "HwjrPzXD2LiotV6uFwMEzRYPKWw9FcVbnMk2vCW4mBPu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "../solana-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
